import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f2f2f2",
  },
  notificationIcon: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    color: "#066E3A",
  },
  HomeTitle: {
    fontSize: 18,
    color: "#066E3A",
    fontWeight: "bold",
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  HomeTitleContainer: {
    backgroundColor: "white",
    borderBottomColor: "#066E3A",
    borderBottomWidth: 2,
    height: 80,
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    backgroundColor: "#fff",
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    paddingHorizontal: 10,
    marginRight: 10,
    height: 40,
    borderRadius: 5,
  },
  inputFocused: {
    borderColor: "#066E3A",
    borderWidth: 1.4,
  },
  searchInputButton: {
    backgroundColor: "#066E3A",
    padding: 10,
    borderRadius: 5,
  },
  searchButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  focusedItem: {
    borderBottomWidth: 2.5,
    borderBottomColor: "#66BB6A",
    borderRadius: 5,
    paddingBottom: 5,
  },
  navbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    backgroundColor: "white",
    padding: 5,
    width: "100%",
    height: 80,
    position: "absolute",
    bottom: 0,
  },
  navbarText: {
    color: "#066E3A",
    fontSize: 12.5,
    fontWeight: "bold",
  },
  navItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: 10,
    borderRadius: 5,
    overflow: "hidden",
  },
  map: {
    width: "100%",
    height: "75.6%",
  },
  buttonModal: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "100%",
    marginTop: 20,
  },
  saveButtonModal: {
    backgroundColor: "#066E3A",
    borderRadius: 5,
    width: 150,
    marginRight: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  cancelButtonModal: {
    backgroundColor: "#BF0000",
    borderRadius: 5,
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
  },
  calloutView: {
    width: 200,
    padding: 10,
  },
  calloutTitle: {
    fontWeight: "bold",
    marginBottom: 5,
  },
  modalContent: {
    flex: 1,
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    margin: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
  },
  input: {
    borderBottomWidth: 1,
    marginBottom: 10,
    padding: 8,
    width: "100%",
  },
  buttonOpenModal: {
    position: "absolute",
    bottom: 100,
    right: 20,
    backgroundColor: "#066E3A",
    padding: 15,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    textAlign: "center",
  },
  buttonCloseModal: {
    backgroundColor: "#BF0000",
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 20,
    alignItems: "center",
    width: "100%",
  },
  loadingText: {
    textAlign: "center",
    marginTop: 20,
    color: "#066E3A",
    fontSize: 16,
  },
  errorText: {
    textAlign: "center",
    marginTop: 20,
    color: "#BF0000",
    fontSize: 16,
  },
});

export default styles;
